In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.0


In [6]:
# Building Tensors

In [3]:
hello = tf.constant("Hello ")

In [4]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [5]:
tf.print(hello)

Hello 


In [7]:
world = tf.constant("World ")

In [8]:
type(world)

tensorflow.python.framework.ops.EagerTensor

In [9]:
tf.print(world)

World 


In [11]:
result = hello + world

tf.print(result)

Hello World 


In [12]:
a = tf.constant(10)

In [13]:
b = tf.constant(20)

In [14]:
a + b

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [16]:
tf.print(a + b)

30


In [17]:
# Array Tensors
myarr = tf.fill((5,5),5)

In [18]:
tf.print(myarr) # Prints a tensor array

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [19]:
myarr.numpy()   # Creates a numpy array

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [20]:
a = tf.constant([[4,5],[6,6]])
a.get_shape()

TensorShape([2, 2])

In [21]:
b = tf.constant([[8],[9]])
b.get_shape()

TensorShape([2, 1])

In [22]:
# Creating tensor with normal distribution of random numbers
mytensor = tf.random.normal((4,4),0,1) # First, pass the size of the distribution(4,4), then the mean of the distribution(0),
# then the standard deviation(1). These values are set by the user. Mean(0) and sd(1) are standard, normal distributions.
tf.print(mytensor)

[[0.989362657 0.318722427 1.11826897 -0.690536082]
 [0.394115359 -1.08045769 1.16807353 -0.0661730543]
 [0.245779321 -1.46778047 -1.72705638 -0.833461702]
 [0.434653044 -1.13978362 1.72019637 1.39230311]]


In [23]:
# Eager execution
# TensorFlow 1.X required users to manually stitch together an absract syntax tree(a graph, if you will) by
# making tf.*API calls. It then required users to manually compile the abstract syntax tree by passing a set 
# of input and output tensors to a sess.run() call.
# TensorFlow 2.X executes eagerly(like Python normally does) and in 2.X, graphs and sessions fell like implementation
# details. 

In [24]:
# Eager execution verification
if(tf.executing_eagerly()):
    print("Eager Execution is enabled(running operations immediately)\n")
else:
    print("You are not runnung eager execution. Tensorflow version >= 2.0.0" \
         "has eager execution enabled by default.")

Eager Execution is enabled(running operations immediately)



In [27]:
# Disabling eager execution
print(("Turn off eager execution by running: \n{0}\n{1}").format('' \
        "from tensorflow.python.framework.ops import disable_eager_execution", \
        "disable_eager_execution()"))

Turn off eager execution by running: 
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()


In [28]:
# Enabling eager execution
print(("Turn on eager execution by running: \n\n{0}\n\nOr upgrade " \
      "your tensorflow version by running: \n\n{1}").format(
      "tf.compat.v1.enable_eager_execution()",
      "!pip install --upgrade tensorflow\n" \
      "!pip install --upgrade tensorflow-gpu"))

Turn on eager execution by running: 

tf.compat.v1.enable_eager_execution()

Or upgrade your tensorflow version by running: 

!pip install --upgrade tensorflow
!pip install --upgrade tensorflow-gpu


In [29]:
# Simple operations in tensorflow
# Common functions from tensorflow
# 1. Making tensors tf.constant() and tf.Variable()
# 2. Concatenation of two tensors using tf.concat()
# 3. Making tensors with tf.zeros() or tf.ones()
# 4. Reshaping data by tf.reshape()
# 5. Casting tensors to other data types with tf.cast()

In [31]:
# Making a constant tensor (A), that does not change:
A = tf.constant([[4,3],[6,3],[9,8]])

In [32]:
tf.print(A)

[[4 3]
 [6 3]
 [9 8]]


In [33]:
A.numpy()

array([[4, 3],
       [6, 3],
       [9, 8]])

In [39]:
# Making a variable tensor VA, which can change. Variable is uppercase, in this instance.
VA = tf.constant([[1,0],[4,7]])

# Making another tensor(b)
B = tf.constant([[4,4],[7,8],[9,9]])


In [40]:
tf.print(VA)

[[1 0]
 [4 7]]


In [41]:
tf.print(B)

[[4 4]
 [7 8]
 [9 9]]


In [43]:
# Concatenation by tf.concat

# Concatenating columns
AB_concatenated = tf.concat(values= [A,B], axis = 1)
print(f"adding B\"s columns to A: \n{AB_concatenated.numpy()}" )

adding B"s columns to A: 
[[4 3 4 4]
 [6 3 7 8]
 [9 8 9 9]]


In [45]:
# Concatenating rows
AB_concatenated = tf.concat(values = [A,B], axis = 0)
print(f"adding B\'s rows to A: \n{AB_concatenated.numpy()}" )

adding B's rows to A: 
[[4 3]
 [6 3]
 [9 8]
 [4 4]
 [7 8]
 [9 9]]


In [47]:
# Making tensors with tf.zeros() and tf.ones()

# Making a tensor filled with zeros. shape = [rows, columns]
tensor = tf.zeros(shape = [2,4], dtype = tf.int32) # tf.zeros will always be integer type
print(f"Tensor full of zeros as int32, 2 rows and 4 columns:\n{tensor.numpy()}")

Tensor full of zeros as int32, 2 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]]


In [48]:
# Making a tensor filled with ones as type float32
tensor = tf.ones(shape = [4,5], dtype = tf.float32)
print(f"Tensor filled with ones as float32, 4 rows and 5 columns:\n{tensor.numpy()}")

Tensor filled with ones as float32, 4 rows and 5 columns:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [49]:
# Reshaping data using tf.reshape()

# Make a tensor
tensor = tf.constant([[5,2,8],[2,2,7],[5,5,6],[1,3,3]])

In [50]:
# Reshaping the tensor into a shape of: shape = [row, columns]
reshaped_tensor = tf.reshape(tensor = tensor, shape = [1,12])

In [51]:
# Showing the difference
print(f"Tensor before reshape:\n{tensor.numpy()}")
print(f"Tensor after reshape:\n{reshaped_tensor.numpy()}")

Tensor before reshape:
[[5 2 8]
 [2 2 7]
 [5 5 6]
 [1 3 3]]
Tensor after reshape:
[[5 2 8 2 2 7 5 5 6 1 3 3]]


In [53]:
# Casting tensors to other data types with tf.cast()

# Make a tensor
tensor = tf.constant([[1.3,7.5,4.6],[7.2,1.3,8.88],[1.4,7.5,9.34],[8.1,5.4,4.66]], dtype = tf.float32)
tensor_as_int = tf.cast(tensor, tf.int32)

In [54]:
print(f"Tensor with floats:\n{ tensor.numpy()}")
print(f"Tensor cast from float to integer (just remove decimal, no rounding):\n{ tensor_as_int.numpy()}")

Tensor with floats:
[[1.3  7.5  4.6 ]
 [7.2  1.3  8.88]
 [1.4  7.5  9.34]
 [8.1  5.4  4.66]]
Tensor cast from float to integer (just remove decimal, no rounding):
[[1 7 4]
 [7 1 8]
 [1 7 9]
 [8 5 4]]


In [55]:
# Linear algebra operations
# 1. Transpose tensors
# 2. Matrix multiplication
# 3. Element-wise multiplication
# 4. Identity matrix

In [56]:
# Transpose tensor
A = tf.constant([[9,7,6],[1,5,7]])
A = tf.transpose(A)
print(f"The transposed matrix:\n{A}")

The transposed matrix:
[[9 1]
 [7 5]
 [6 7]]


In [58]:
# Matrix multiplication: All elements of first row matrix are multilpied with element of first row vector, and so on. 
# Some matrix(A)
A = tf.constant([[3,7],[1,9]])  #2x2 matrix
# Some vector v
v = tf.constant([[7],[4]])  # 2x1 vector
# Matrix multiplication of A * v^T
Av = tf.matmul(A,v)
print(f"Matrix multiplication of A and v results in a new tensor:\n{Av}")

Matrix multiplication of A and v results in a new tensor:
[[49]
 [43]]


In [59]:
# Element-wise multiplication
Av = tf.multiply(A, v)
print(f"Element-wise multiplication of A and v results in a new tensor:\n{Av}")
# Comparing matrix and element-wise multiplication, we can see they are different.

Element-wise multiplication of A and v results in a new tensor:
[[21 49]
 [ 4 36]]


In [60]:
# Identity matrix
A = tf.constant([[3,7],[1,9]])
v = tf.constant([[7],[4]])

In [61]:
# Get number of dimensions
rows, columns = A.shape
print(f"Get rows and columns in tensor A:\n{rows} rows\n{columns} columns")

Get rows and columns in tensor A:
2 rows
2 columns


In [63]:
# Making identity matrix
A_identity = tf.eye(num_rows = rows, num_columns = columns, dtype = tf.int32)
print(f"\nThe identity matrix of A:\n{A_identity.numpy()}")


The identity matrix of A:
[[1 0]
 [0 1]]


In [64]:
# Matrix multiplication of A.A_identity
AAt = tf.matmul(A,A_identity)
print(f"Matrix multiplication of A and v results in a new tensor:\n{AAt}")

Matrix multiplication of A and v results in a new tensor:
[[3 7]
 [1 9]]


In [67]:
# Creating a variable in TensorFlow
# To use the value of a tf.Variable in a TensorFlow graph, simply treat it like a tf.Tensor
my_variable = tf.Variable(tf.zeros([2, 3, 4]))  # Two tensors with three rows and four columns

In [69]:
tf.print(my_variable)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [73]:
v = tf.Variable(0.0)
w = v + 1  # w is a tf.Tensor which is computed on the value of y
           # Anytime a variable is used in an expression, it get automatically converted to a tf.Tensor
           # representng it's value.
tf.print(v)
tf.print(w)

0
1


In [76]:
v = tf.Variable(0.0)
v.assign(2)   # Using assign method to change value of (v) to 2. Also, you can add .numpy() to get a numpy array

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [77]:
tf.print(v)

2


In [78]:
v = tf.Variable(0.0)
v.assign_add(1)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=1.0>

In [79]:
tf.print(v)

1


In [80]:
# Operations in Tensorflow 2.0
# Functions, not sessions!!
# TensorFlow 1.0: 
# outputs = session.run(f(placeholder), feed_dict = {placeholder.input})

# TensorFlow 2.0:
# outputs = f(input)

In [81]:
def add_op(a,b):
    return a + b

In [82]:
print(add_op(10,20))

30


In [84]:
# Linear model
W = tf.Variable([10], tf.int32)
b = tf.Variable([5], tf.int32)

In [85]:
# Build the model
def linear_model(x):
    return W*x + b

In [86]:
linear_model(x = [5,10,15,20])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 55, 105, 155, 205])>

In [87]:
linear_model(x = [5,10,15,20]).numpy()  # Add numpy() to return a numpy array

array([ 55, 105, 155, 205])