In [1]:
python3 --version

NameError: name 'python3' is not defined

In [2]:
import tensorflow as tf
import numpy as np

## Types of tensors
#### Tensors are multi-dimensional arrays with a uniform type
#### All tensors are immutable like Python numbers and strings
#### Meaning you can never update the contents of one. You can only create a new one.

In [3]:
a = np.array([[1,2,3],[4,5,6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
a.shape

(2, 3)

In [6]:
x = tf.constant(24, name = "x")  #this constant is immutable
y = tf.Variable(x + 10, name = "y")  #the variable, of course, can change

In [7]:
print(x)

tf.Tensor(24, shape=(), dtype=int32)


In [8]:
import keras

In [9]:
model = tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session() as session:
    session.run(model)
    print(session.run(y))

RuntimeError: The Session graph is empty. Add operations to the graph before calling run().

In [10]:
rank_0_tensor = tf.constant(4) #int32 tensor by default. Also known as "scalar".

In [11]:
print(rank_0_tensor) #Data type of integer

tf.Tensor(4, shape=(), dtype=int32)


In [12]:
rank_1_tensor = tf.constant([2.0,3.0,4.0])
#A rank one tensor, or "vector", is like a list of values

In [13]:
print(rank_1_tensor) #Data type of float32

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [14]:
#A rank-2 tensor has two axes. Also called a matrix. 
#A scalar shape: []  A vector shape:[3]  A matrix shape:[3,2]

In [15]:
rank_2_tensor = tf.constant([[1,2],[3,4],[5,6]], dtype = "float16") #Change data type

In [16]:
print(rank_2_tensor) 

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [17]:
#A tensor may have more axes.

In [18]:
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],
    [5,6,7,8,9]],
    [[10,11,12,13,14],
    [15,16,17,18,19]],
    [[20,21,22,23,24],
    [25,26,27,28,29]],])

In [19]:
print (rank_3_tensor) #This 3-axis tensor shape is [3,2,5]

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [20]:
#You can convert a tensor to a numpy array either using np.array or tensor.numpy method
np.array(rank_2_tensor)
#    rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

#### Equations for back propagation and gradient descent

In [21]:
import numpy as np
import pandas as pd

In [22]:
## Equation y = w1.x1 + w2.x2

In [23]:
x1 = 2
x2 = 5
y = 31

In [24]:
lr = 0.01  #lr = learning rate(very important for accuracy) Can't be too large or too small
w1 = 3
w2 = 7

In [25]:
for epoch in range(50):
    y_pred = w1*x1 + w2*x2
    error = (y - y_pred)**2
    dEw1 = 2*(y - y_pred) * (-x1)
    dEw2 = 2*(y - y_pred) * (-x2)
    
    w1 = w1 - lr*dEw1
    w2 = w2 - lr*dEw2
    print ("Value of w1 - ", w1, "Value of w2 - ", w2, "Error is -", error)

Value of w1 -  2.6 Value of w2 -  6.0 Error is - 100
Value of w1 -  2.432 Value of w2 -  5.58 Error is - 17.640000000000025
Value of w1 -  2.36144 Value of w2 -  5.403600000000001 Error is - 3.111695999999985
Value of w1 -  2.3318048 Value of w2 -  5.329512 Error is - 0.5489031744000062
Value of w1 -  2.319358016 Value of w2 -  5.29839504 Error is - 0.09682651996416189
Value of w1 -  2.3141303667199997 Value of w2 -  5.285325916800001 Error is - 0.01708019812167695
Value of w1 -  2.3119347540223996 Value of w2 -  5.2798368850560005 Error is - 0.0030129469486645474
Value of w1 -  2.3110125966894075 Value of w2 -  5.27753149172352 Error is - 0.0005314838417443082
Value of w1 -  2.310625290609551 Value of w2 -  5.276563226523878 Error is - 9.375374968372762e-05
Value of w1 -  2.3104626220560114 Value of w2 -  5.276156555140029 Error is - 1.6538161444169675e-05
Value of w1 -  2.3103943012635244 Value of w2 -  5.275985753158812 Error is - 2.9173316787665796e-06
Value of w1 -  2.310365606530

In [26]:
print (w1, w2)

2.3103448275862073 5.275862068965518


In [27]:
x1*w1 + x2*w2

31.0